/* **DISCLAIMER**
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * Without limitation of the foregoing, Contributors/Regents expressly does not warrant that:
 * 1. the software will meet your requirements or expectations;
 * 2. the software or the software content will be free of bugs, errors, viruses or other defects;
 * 3. any results, output, or data provided through or generated by the software will be accurate, up-to-date, complete or reliable;
 * 4. the software will be compatible with third party software;
 * 5. any errors in the software will be corrected.
 * The user assumes all responsibility for selecting the software and for the results obtained from the use of the software. The user shall bear the entire risk as to the quality and the performance of the software.
 */ 
 
/**
 * Foscam IP Camera
 *
 * Taken from skp19, Enhanced and bugfixed by RBoy
 * Changes Copyright RBoy, redistribution of any changes or modified code is not allowed without permission
 * Change log:
 * 2015-2-22 - Fix for Alarm and Switch not being updated
 * 2015-2-4 - Presets show names
 * 2015-1-29 - Added options for configuring eMail, local ringer alarm, taking pictures and recording videos for motion detection
 * 2015-1-20 - Cruisemaps now show the names
 * 2015-1-20 - Added support for hostnames (public) instead of ipaddress for device
 * 2015-1-19 - Turning on the strobe function also takes a picture
 * 2015-1-19 - Support configuring motion alarm snap interval and motion sensitivity, added support for using as an Alarm and Switch/Relay Switch to enable monitoring
 *
 *  This device has the following functions:
 *    - Take a snapshot
 *    - Toggle the infrared lights
 *    - Enable/Disable motion alarm
 *    - Go to and set preset locations
 *    - Enable cruise maps
 *    - Control PTZ
 *    - Reboot
 *
 *  Capability: Image Capture, Polling, Alarm, Relay Switch, Switch
 *  Custom Attributes: hubactionMode, alarmStatus, ledStatus, cruise1, cruise2
 *  Custom Commands: alarmOn, alarmOff, toggleAlarm, left, right, up, down,
 *                   stop, set, preset, preset1, preset2, preset3, cruisemap1,
 *                   cruisemap2, cruise, toggleLED, ledOn, ledOff, ledAuto
 *
 */
 
metadata {
	definition (name: "Foscam IP Camera", namespace: "rboy", author: "RBoy") {
		capability "Polling"
		capability "Image Capture"
        capability "Alarm"
        capability "Relay Switch"
        capability "Switch"
        capability "Refresh"
        
        attribute "alarmStatus", "string"
        attribute "ledStatus",   "string"
        attribute "hubactionMode", "string"
        attribute "cruise1", "string"
        attribute "cruise2", "string"
        attribute "presetA", "string"
        attribute "presetB", "string"
        attribute "presetC", "string"
    
		command "alarmOn"
		command "alarmOff"
		command "toggleAlarm"
		command "toggleLED"
        
		command "ledOn"
		command "ledOff"
		command "ledAuto"
        
		command "left"
		command "right"
		command "up"
		command "down"
        
		command "cruisemap1"
		command "cruisemap2"
		command "stopCruise"
        
		command "preset1"
		command "preset2"
		command "preset3"
        
        command "reboot"
	}
    
    preferences {
        input("ip", "string", title:"Camera IP Address/URL", description: "Camera IP Address or Hostname", required: true, displayDuringSetup: true)
        input("port", "string", title:"Camera Port", description: "Camera Port", defaultValue: "80" , required: true, displayDuringSetup: true)
        input("username", "string", title:"Camera Username", description: "Camera Username", required: true, displayDuringSetup: true)
        input("password", "password", title:"Camera Password", description: "Camera Password", required: true, displayDuringSetup: true)
        input("hdcamera", "bool", title:"HD Foscam Camera? (9xxx Series)", description: "Type of Foscam Camera", required: true, displayDuringSetup: true)
        input("mirror", "bool", title:"Mirror? (Not required for HD cameras)", description: "Camera Mirrored?")
        input("flip", "bool", title:"Flip? (Not required for HD cameras)", description: "Camera Flipped?")
        input("motionLevel", "enum", title:"Motion Detect Sensitivity Level (For HD cameras only)", multiple: false, defaultValue: "Medium", metadata:[values:["Lowest","Lower","Low","Medium","High"]], description: "Alarm Motion Sensitivity Level", required: true, displayDuringSetup: true)
        input("snapInterval", "enum", title:"Motion Detect Snap Interval (For HD cameras only)", multiple: false, defaultValue: "15s", metadata:[values:["5s","6s","7s","8s","9s","10s","11s","12s","13s","14s","15s"]], description: "Alarm Motion Snap Interval in seconds", required: true, displayDuringSetup: true)
        input("motionRing", "bool", title:"Motion Detect Alarm (For HD cameras only)", description: "Sound local ring alarm when motion is detected", defaultValue: true, required: true, displayDuringSetup: true)
        input("motionEMail", "bool", title:"Motion Detect EMail (For HD cameras only)", description: "Send e-Mail when motion is detected", defaultValue: true, required: true, displayDuringSetup: true)
        input("motionSnap", "bool", title:"Motion Detect Take Picture (For HD cameras only)", description: "Take a picture when motion is detected", defaultValue: true, required: true, displayDuringSetup: true)
        input("motionRecord", "bool", title:"Motion Detect Record Video (For HD cameras only)", description: "Record a video when motion is detected", defaultValue: true, required: true, displayDuringSetup: true)
		input("preset1", "text", title: "Preset 1 (For HD cameras only)", description: "Name of your first preset position")
		input("preset2", "text", title: "Preset 2 (For HD cameras only)", description: "Name of your second preset position")
		input("preset3", "text", title: "Preset 3 (For HD cameras only)", description: "Name of your third preset position")
		input("cruisename1", "text", title: "Cruise Map 1 (For HD cameras only. Non-HD cameras will default to Horizontal.)", description: "Name of your first cruise map", defaultValue: "Horizontal")
		input("cruisename2", "text", title: "Cruise Map 2 (For HD cameras only. Non-HD cameras will default to Vertical.)", description: "Name of your second cruise map", defaultValue: "Vertical")
	}

	tiles {
        carouselTile("cameraDetails", "device.image", width: 3, height: 2) { }

        standardTile("camera", "device.alarmStatus", width: 1, height: 1, canChangeIcon: true, inactiveLabel: true, canChangeBackground: true) {
          state "off", label: "off", action: "toggleAlarm", icon: "st.Lighting.light15", backgroundColor: "#FFFFFF"
          state "on", label: "on", action: "toggleAlarm", icon: "st.Lighting.light15",  backgroundColor: "#53A7C0"
        }

		standardTile("take", "device.image", width: 1, height: 1, canChangeIcon: false, inactiveLabel: true, canChangeBackground: false) {
			state "take", label: "Take", action: "Image Capture.take", icon: "st.camera.camera", backgroundColor: "#FFFFFF", nextState:"taking"
			state "taking", label:'Taking', action: "", icon: "st.camera.take-photo", backgroundColor: "#53a7c0"
			state "image", label: "Take", action: "Image Capture.take", icon: "st.camera.camera", backgroundColor: "#FFFFFF", nextState:"taking"
		}

        standardTile("alarmStatus", "device.alarmStatus", width: 1, height: 1, canChangeIcon: true, inactiveLabel: true, canChangeBackground: true) {
          state "off", label: "off", action: "toggleAlarm", icon: "st.Lighting.light15", backgroundColor: "#FFFFFF"
          state "on", label: "on", action: "toggleAlarm", icon: "st.Lighting.light15",  backgroundColor: "#53A7C0"
        }
        
        standardTile("ledStatus", "device.ledStatus", width: 1, height: 1, canChangeIcon: false, inactiveLabel: true, canChangeBackground: false) {
          state "auto", label: "auto", action: "toggleLED", icon: "st.lights.multi-light-bulb-off", backgroundColor: "#53A7C0"
          state "off", label: "off", action: "toggleLED", icon: "st.lights.multi-light-bulb-off", backgroundColor: "#FFFFFF"
          state "on", label: "on", action: "toggleLED", icon: "st.lights.multi-light-bulb-on", backgroundColor: "#FFFF00"
          state "manual", label: "manual", action: "toggleLED", icon: "st.lights.multi-light-bulb-off", backgroundColor: "#FFFF00"
        }
        
        standardTile("ledAuto", "device.ledStatus", width: 1, height: 1, canChangeIcon: false, inactiveLabel: true, canChangeBackground: false) {
          state "auto", label: "auto", action: "ledAuto", icon: "st.lights.multi-light-bulb-on", backgroundColor: "#53A7C0"
          state "off", label: "auto", action: "ledAuto", icon: "st.lights.multi-light-bulb-off", backgroundColor: "#FFFFFF"
          state "on", label: "auto", action: "ledAuto", icon: "st.lights.multi-light-bulb-off", backgroundColor: "#FFFFFF"
          state "manual", label: "auto", action: "ledAuto", icon: "st.lights.multi-light-bulb-off", backgroundColor: "#FFFFFF"
        }

        standardTile("ledOn", "device.ledStatus", width: 1, height: 1, canChangeIcon: false, inactiveLabel: true, canChangeBackground: false) {
          state "auto", label: "on", action: "ledOn", icon: "st.lights.multi-light-bulb-on", backgroundColor: "#FFFFFF"
          state "off", label: "on", action: "ledOn", icon: "st.lights.multi-light-bulb-on", backgroundColor: "#FFFFFF"
          state "on", label: "on", action: "ledOn", icon: "st.lights.multi-light-bulb-on", backgroundColor: "#FFFF00"
          state "manual", label: "on", action: "ledOn", icon: "st.lights.multi-light-bulb-on", backgroundColor: "#00FF00"
        }
        
        standardTile("ledOff", "device.ledStatus", width: 1, height: 1, canChangeIcon: false, inactiveLabel: true, canChangeBackground: false) {
          state "auto", label: "off", action: "ledOff", icon: "st.lights.multi-light-bulb-off", backgroundColor: "#FFFFFF"
          state "off", label: "off", action: "ledOff", icon: "st.lights.multi-light-bulb-off", backgroundColor: "#53A7C0"
          state "on", label: "off", action: "ledOff", icon: "st.lights.multi-light-bulb-off", backgroundColor: "#FFFFFF"
          state "manual", label: "off", action: "ledOff", icon: "st.lights.multi-light-bulb-off", backgroundColor: "#00FF00"
        }
        
		standardTile("preset1", "device.presetA", width: 1, height: 1, canChangeIcon: false, canChangeBackground: false, decoration: "flat") {
			state "preset1", label: '${currentValue}', action: "preset1", icon: ""
		}

		standardTile("preset2", "device.presetB", width: 1, height: 1, canChangeIcon: false, canChangeBackground: false, decoration: "flat") {
			state "preset2", label: '${currentValue}', action: "preset2", icon: ""
		}

		standardTile("preset3", "device.presetC", width: 1, height: 1, canChangeIcon: false, canChangeBackground: false, decoration: "flat") {
			state "preset3", label: '${currentValue}', action: "preset3", icon: ""
		}
        
		standardTile("cruisemap1", "device.cruise1", width: 1, height: 1, canChangeIcon: false, canChangeBackground: false, decoration: "flat") {
			state "cruisemap1", label: '${currentValue}', action: "cruisemap1", icon: ""
		}

		standardTile("cruisemap2", "device.cruise2", width: 1, height: 1, canChangeIcon: false, canChangeBackground: false, decoration: "flat") {
			state "cruisemap2", label: '${currentValue}', action: "cruisemap2", icon: ""
		}
 
 		standardTile("stopcruise", "device.image", width: 1, height: 1, canChangeIcon: false, canChangeBackground: false, decoration: "flat") {
			state "stopcruise", label: "Stop Cruise", action: "stopCruise", icon: ""
		}

		standardTile("left", "device.image", width: 1, height: 1, canChangeIcon: false,  canChangeBackground: false, decoration: "flat") {
			state "left", label: "left", action: "left", icon: "st.thermostat.thermostat-left"
		}

		standardTile("right", "device.image", width: 1, height: 1, canChangeIcon: false,  canChangeBackground: false, decoration: "flat") {
			state "right", label: "right", action: "right", icon: "st.thermostat.thermostat-right"
		}

		standardTile("up", "device.image", width: 1, height: 1, canChangeIcon: false, canChangeBackground: false, decoration: "flat") {
			state "up", label: "up", action: "up", icon: "st.thermostat.thermostat-up"
		}

		standardTile("down", "device.image", width: 1, height: 1, canChangeIcon: false, canChangeBackground: false, decoration: "flat") {
			state "down", label: "down", action: "down", icon: "st.thermostat.thermostat-down"
		}

		standardTile("stop", "device.image", width: 1, height: 1, canChangeIcon: false,  canChangeBackground: false, decoration: "flat") {
			state "stop", label: "", action: "stopCruise", icon: "st.sonos.stop-btn"
		}

        standardTile("refresh", "device.alarmStatus", inactiveLabel: false, decoration: "flat") {
        	state "refresh", action:"refresh.refresh", icon:"st.secondary.refresh"
        }
        
        standardTile("blank", "device.image", width: 1, height: 1, canChangeIcon: false,  canChangeBackground: false, decoration: "flat") {
        	state "blank", label: "", action: "", icon: "", backgroundColor: "#FFFFFF"
        }
        
        standardTile("reboot", "device.image", inactiveLabel: false, decoration: "flat") {
      		state "reboot", label: "reboot", action: "reboot", icon: "st.quirky.spotter.quirky-spotter-plugged"
    	}

        main "camera"
			details(["cameraDetails", "take", "blank", "alarmStatus", "ledAuto", "ledOn", "ledOff", "preset1", "preset2", "preset3", "cruisemap1", "cruisemap2", "stopcruise", "blank", "up", "blank", "left", "stop", "right", "blank", "down", "blank", "refresh", "reboot"])
	}
}

groovy.json.JsonSlurper

//TAKE PICTURE
def take() {
	log.debug("Taking Photo")
	sendEvent(name: "hubactionMode", value: "s3");
    if(hdcamera == "true") {
		hubGet("cmd=snapPicture2")
    }
    else {
    	hubGet("/snapshot.cgi?")
    }
}
//END TAKE PICTURE

//SWITCH ACTIONS
def on() {
	log.debug "On requested, enabling monitoring"
    alarmOn()
}

def off() {
	log.debug "Off requested, disabling monitoring"
    alarmOff()
}
//END SWITCH ACTIONS

//ALARM ACTIONS
def strobe() {
	log.debug "Alarm strobe requested, enabling monitoring and taking picture"
    take()
    alarmOn()
}

def toggleAlarm() {
	log.debug "Toggling Alarm"
	if(device.currentValue("alarmStatus") == "on") {
    	alarmOff()
  	}
	else {
    	alarmOn()
	}
}

def alarmOn() {
	log.debug "Enabling Alarm"
    sendEvent(name: "alarmStatus", value: "on");
    if(hdcamera == "true") {
		delayBetween([hubGet("cmd=setMotionDetectConfig&isEnable=1&snapInterval=1&sensitivity=${getMotionLevel(motionLevel)}&linkage=${getMotionAlarmEvents()}&triggerInterval=${getSnapInterval(snapInterval)}&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&1421696056773"), poll()])
    }
    else {
    	delayBetween([hubGet("/set_alarm.cgi?motion_armed=1&"), poll()])
    }
}

def alarmOff() {
	log.debug "Disabling Alarm"
    sendEvent(name: "alarmStatus", value: "off");
    if(hdcamera == "true") {
		delayBetween([hubGet("cmd=setMotionDetectConfig&isEnable=0"), poll()])
    }
    else {
    	delayBetween([hubGet("/set_alarm.cgi?motion_armed=0&"), poll()])
    }
}
//END ALARM ACTIONS

//LED ACTIONS
//Toggle LED's
def toggleLED() {
  log.debug("Toggle LED")

  if(device.currentValue("ledStatus") == "auto") {
    ledOn()
  }

  else if(device.currentValue("ledStatus") == "on") {
    ledOff()
  }
  
  else {
    ledAuto()
  }
}

def ledOn() {
    log.debug("LED changed to: on")
    sendEvent(name: "ledStatus", value: "on");
    if(hdcamera == "true") {
	    delayBetween([hubGet("cmd=setInfraLedConfig&mode=1"), hubGet("cmd=openInfraLed")])
    }
    else {
    	hubGet("/decoder_control.cgi?command=95&")
    }
}

def ledOff() {
    log.debug("LED changed to: off")
    sendEvent(name: "ledStatus", value: "off");
    if(hdcamera == "true") {
    	delayBetween([hubGet("cmd=setInfraLedConfig&mode=1"), hubGet("cmd=closeInfraLed")])
    }
    else {
    	hubGet("/decoder_control.cgi?command=94&")
    }
}

def ledAuto() {
    log.debug("LED changed to: auto")
    sendEvent(name: "ledStatus", value: "auto");
	if(hdcamera == "true") {
		hubGet("cmd=setInfraLedConfig&mode=0")
    }
    else {
    	hubGet("/decoder_control.cgi?command=95&")
    }
}
//END LED ACTIONS

//PRESET ACTIONS
def preset1() {
	log.debug("Preset 1 Selected - ${preset1}")
	if(hdcamera == "true") {
		hubGet("cmd=ptzGotoPresetPoint&name=${preset1}")
    }
    else {
    	hubGet("/decoder_control.cgi?command=31&")
    }
}

def preset2() {
	log.debug("Preset 2 Selected - ${preset2}")
	if(hdcamera == "true") {
		hubGet("cmd=ptzGotoPresetPoint&name=${preset2}")
    }
    else {
    	hubGet("/decoder_control.cgi?command=33&")
    }
}

def preset3() {
	log.debug("Preset 3 Selected - ${preset3}")
	if(hdcamera == "true") {
		hubGet("cmd=ptzGotoPresetPoint&name=${preset3}")
    }
    else {
    	hubGet("/decoder_control.cgi?command=35&")
    }
}
//END PRESET ACTIONS

//CRUISE ACTIONS
def cruisemap1() {
	log.debug("Cruise Map 1 Selected - ${cruisename1}")
	if(hdcamera == "true") {
		hubGet("cmd=ptzStartCruise&mapName=${cruisename1}")
    }
    else {
    	hubGet("/decoder_control.cgi?command=28&")
    }
}

def cruisemap2() {
	log.debug("Cruise Map 2 Selected - ${cruisename2}")
	if(hdcamera == "true") {
		hubGet("cmd=ptzStartCruise&mapName=${cruisename2}")
    }
    else {
    	hubGet("/decoder_control.cgi?command=26&")
    }
}

def stopCruise() {
	log.debug("Stop Cruise")
	if(hdcamera == "true") {
		hubGet("cmd=ptzStopRun")
    }
    else {
    	delayBetween([hubGet("/decoder_control.cgi?command=29&"), hubGet("/decoder_control.cgi?command=27&")])
    }
}
//END CRUISE ACTIONS

//PTZ CONTROLS
def left() {
	if(hdcamera == "true") {
		delayBetween([hubGet("cmd=ptzMoveLeft"), hubGet("cmd=ptzStopRun")])
    }
    else {
    	if(mirror == "true") {
	    	hubGet("/decoder_control.cgi?command=4&onestep=1&")
        }
        else {
        	hubGet("/decoder_control.cgi?command=6&onestep=1&")
        }
    }
}

def right() {
	if(hdcamera == "true") {
		delayBetween([hubGet("cmd=ptzMoveRight"), hubGet("cmd=ptzStopRun")])
    }
    else {
    	if(mirror == "true") {
	    	hubGet("/decoder_control.cgi?command=6&onestep=1&")
        }
        else {
        	hubGet("/decoder_control.cgi?command=4&onestep=1&")
        }
    }
}

def up() {
	if(hdcamera == "true") {
        delayBetween([hubGet("cmd=ptzMoveUp"), hubGet("cmd=ptzStopRun")])
    }
    else {
    	if(flip == "true") {
	    	hubGet("/decoder_control.cgi?command=2&onestep=1&")
        }
        else {
        	hubGet("/decoder_control.cgi?command=0&onestep=1&")
        }
    }
}

def down() {
	if(hdcamera == "true") {
        delayBetween([hubGet("cmd=ptzMoveDown"), hubGet("cmd=ptzStopRun")])
    }
    else {
    	if(flip == "true") {
    		hubGet("/decoder_control.cgi?command=0&onestep=1&")
        }
        else {
        	hubGet("/decoder_control.cgi?command=2&onestep=1&")
        }
    }
}
//END PTZ CONTROLS

//REBOOT
def reboot() {
	if(hdcamera == "true") {
		hubGet("cmd=rebootSystem")
    }
    else {
    	hubGet("/reboot.cgi?&" + $getLogin())
    }
}
//END REBOOT

def refresh() {
	log.debug("Refresh called")
	poll()
}

def poll() {

	//Update the tiles names
    sendEvent(name: "cruise1", value: "$cruisename1 Cruise")
    sendEvent(name: "cruise2", value: "$cruisename2 Cruise")
    sendEvent(name: "presetA", value: "Preset $preset1")
    sendEvent(name: "presetB", value: "Preset $preset2")
    sendEvent(name: "presetC", value: "Preset $preset3")

	sendEvent(name: "hubactionMode", value: "local");
    //Poll Motion Alarm Status and IR LED Mode
    if(hdcamera == "true") {
		delayBetween([hubGet("cmd=getMotionDetectConfig"), hubGet("cmd=getInfraLedConfig")])
    }
    else {
    	hubGet("/get_params.cgi?")
    }
}

private getLogin() {
	if(hdcamera == "true") {
    	return "usr=${username}&pwd=${password}&"
    }
    else {
    	return "user=${username}&pwd=${password}"
    }
}

private hubGet(def apiCommand) {
	// Check if we have a hostname and if so convert to IP Address
    if (!isIPAddress(ip)) {
        log.debug("Converting hostname $ip to IP Address before continuing")
        state.ipAddress = convertHostnameToIPAddress(ip)
        log.debug("Got IPAddress=${state.ipAddress} for hostname=$ip")
    }
    else {
        state.ipAddress = ip
    }
    
	//Setting Network Device Id
    def iphex = convertIPtoHex(state.ipAddress)
    def porthex = convertPortToHex(port)
    device.deviceNetworkId = "$iphex:$porthex"
    log.debug "Device Network Id set to ${iphex}:${porthex}"

	log.debug("Executing hubaction on " + getHostAddress())
    def uri = ""
    if(hdcamera == "true") {
    	uri = "/cgi-bin/CGIProxy.fcgi?" + getLogin() + apiCommand
	}
    else {
    	uri = apiCommand + getLogin()
    }
    log.debug uri
    def hubAction = new physicalgraph.device.HubAction(
    	method: "GET",
        path: uri,
        headers: [HOST:getHostAddress()]
    )
    if(device.currentValue("hubactionMode") == "s3") {
        hubAction.options = [outputMsgToS3:true]
        sendEvent(name: "hubactionMode", value: "local");
    }
	hubAction
}

//Parse events into attributes
def parse(String description) {
	log.debug "Parsing '${description}'"
    
    def map = [:]
    def retResult = []
    def descMap = parseDescriptionAsMap(description)
        
    //Image
	if (descMap["bucket"] && descMap["key"]) {
		putImageInS3(descMap)
	}

	//Status Polling
    else if (descMap["headers"] && descMap["body"]) {
        def body = new String(descMap["body"].decodeBase64())
        if(hdcamera == "true") {
            def langs = new XmlSlurper().parseText(body)
            
            def motionAlarm = "$langs.isEnable"
            def ledMode = "$langs.mode"

            //Get Motion Alarm Status
            if(motionAlarm == "0") {
                log.info("Polled: Alarm Off")
                sendEvent(name: "alarmStatus", value: "off");
                sendEvent(name: "alarm", value: "off");
                sendEvent(name: "switch", value: "off");
            }
            else if(motionAlarm == "1") {
                log.info("Polled: Alarm On")
                sendEvent(name: "alarmStatus", value: "on");
                sendEvent(name: "alarm", value: "both");
                sendEvent(name: "switch", value: "on");
            }

            //Get IR LED Mode
            if(ledMode == "0") {
                log.info("Polled: LED Mode Auto")
                sendEvent(name: "ledStatus", value: "auto")
            }
            else if(ledMode == "1") {
                log.info("Polled: LED Mode Manual")
                sendEvent(name: "ledStatus", value: "manual")
            }
    	}
        else {
        	if(body.find("alarm_motion_armed=0")) {
				log.info("Polled: Alarm Off")
                sendEvent(name: "alarmStatus", value: "off")
                sendEvent(name: "alarm", value: "off");
                sendEvent(name: "switch", value: "off");
            }
        	else if(body.find("alarm_motion_armed=1")) {
				log.info("Polled: Alarm On")
                sendEvent(name: "alarmStatus", value: "on")
                sendEvent(name: "alarm", value: "both");
                sendEvent(name: "switch", value: "on");
            }
            //The API does not provide a way to poll for LED status on 8xxx series at the moment
        }
	}
}

def parseDescriptionAsMap(description) {
	description.split(",").inject([:]) { map, param ->
		def nameAndValue = param.split(":")
		map += [(nameAndValue[0].trim()):nameAndValue[1].trim()]
	}
}

def putImageInS3(map) {

	def s3ObjectContent

	try {
		def imageBytes = getS3Object(map.bucket, map.key + ".jpg")

		if(imageBytes)
		{
			s3ObjectContent = imageBytes.getObjectContent()
			def bytes = new ByteArrayInputStream(s3ObjectContent.bytes)
			storeImage(getPictureName(), bytes)
		}
	}
	catch(Exception e) {
		log.error e
	}
	finally {
		//Explicitly close the stream
		if (s3ObjectContent) { s3ObjectContent.close() }
	}
}

private getPictureName() {
  def pictureUuid = java.util.UUID.randomUUID().toString().replaceAll('-', '')
  "image" + "_$pictureUuid" + ".jpg"
}

private getHostAddress() {
	return "${state.ipAddress}:${port}"
}

private String convertIPtoHex(ipAddress) {   // thanks to @pstuart
    String hex = ipAddress.tokenize( '.' ).collect {  String.format( '%02x', it.toInteger() ) }.join()
    return hex

}

private String convertPortToHex(port) {  // thanks to @pstuart
	String hexport = port.toString().format( '%04x', port.toInteger() )
    return hexport
}

private String getMotionLevel(motion) {
	log.debug("Motion Level is $motion")

	String retVal = ""
    
    switch (motion) {
    	case "Lowest":
        	retVal = "4"
            break;
            
    	case "Lower":
        	retVal = "3"
            break;
            
    	case "Low":
        	retVal = "0"
            break;
            
    	case "Medium":
        	retVal = "1"
            break;
            
    	case "High":
        	retVal = "2"
            break;
            
		default:
        	retVal = "1"
            break;
    }
    
    log.debug("Motion value is $retVal")
    
    return retVal
}

private String getSnapInterval(interval) {
	log.debug("Snap internal is $interval")

	String[][] intervals = [
    							["5s","0"],
                                ["6s","1"], 
                                ["7s","2"], 
                                ["8s","3"], 
                                ["9s","4"], 
                                ["10s","5"], 
                                ["11s","6"], 
                                ["12s","7"], 
                                ["13s","8"], 
                                ["14s","9"], 
                                ["15s","10"]
			    		    ]

	String retVal = ""
    
    switch (interval) {
    	case "5s":
        	retVal = "0"
            break;
            
    	case "6s":
        	retVal = "1"
            break;
            
    	case "7s":
        	retVal = "2"
            break;
            
    	case "8s":
        	retVal = "3"
            break;
            
    	case "9":
        	retVal = "4"
            break;
            
    	case "10s":
        	retVal = "5"
            break;
            
    	case "11s":
        	retVal = "6"
            break;
            
    	case "12s":
        	retVal = "7"
            break;
            
    	case "13s":
        	retVal = "8"
            break;
            
    	case "14s":
        	retVal = "9"
            break;
            
    	case "15s":
        	retVal = "10"
            break;
            
		default:
        	retVal = "10"
            break;
    }

	log.debug("Snap interval value is $retVal")
    
    return retVal
}

private String getMotionAlarmEvents() {
	int ret = 0 // Default nothing to enable
    
    if (motionRing == "true") {
    	ret |= 0x1 // Enable local ringer
	    log.debug "Enabled motion ringer, $ret"
    }
    
    if (motionEMail == "true") {
    	ret |= 0x2 // Enable sending eMails
	    log.debug "Enabled motion eMail, $ret"
    }
    
    if (motionSnap == "true") {
    	ret |= 0x4 // Enable taking pictures
	    log.debug "Enabled motion snap pictures, $ret"
    }
    
    if (motionRecord == "true") {
    	ret |= 0x8 // Enabling taking a video recording
	    log.debug "Enabled motion video recording, $ret"
    }
    
    log.debug "Motion alarm config value $ret"

    return ret.toString()
}

private boolean isIPAddress(String ipAddress)
{
    try
    {
         String[] parts = ipAddress.split("\\.")
         if (parts.length != 4) {
         	return false
         }
         for (int i = 0; i < 4; ++i)
         {
             int p = Integer.parseInt(parts[i])
             if (p > 255 || p < 0) {
             	return false
             }
         }
         return true;
    } catch (Exception e)
    {
        return false;
    }
}

private String convertHostnameToIPAddress(hostname) {
	def params = [
      uri: "http://api.myiponline.net/dig?url=" + hostname // thanks @cosmicpuppy
    ]

	def retVal = null
    
	try {
    	retVal = httpGet(params) { response ->
			log.debug "Request was successful, data=$response.data, status=$response.status"
            for(result in response.data) {
	            for(subresult in result) {
                    if (subresult.type == "A") {
                        log.debug("Hostname $subresult.host has IP Address $subresult.ip")
                        return subresult.ip
                    }
                }
            }
        }
    }
    catch (Exception e) {
    	log.debug("Unable to convert hostname to IP Address, Error: $e")
    }
    
    return retVal
}
